---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- script/**/*
- spec/**/*
- examples/**
- lib/dyph3/two_way_differs/original_heckel_diff.rb
